version: '3.1'

services:
  ho-rabbitmq3:
      container_name: "ho-rabbitmq"
      image: rabbitmq:3.11.9-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
      restart: always
      ports:
          - '5672:5672'
          - '15672:15672'
      volumes:
        - ./configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./configs/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  ho-keycloak:
    container_name: ho-keycloak
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KK_TO_RMQ_URL=ho-rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=guest
      - KK_TO_RMQ_PASSWORD=guest
      - KK_TO_RMQ_VHOST=/
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    restart: always
    volumes:
      - ./resources/keycloak-to-rabbit-3.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-3.0.jar
      - ./configs/keycloak/realm-export.json:/tmp/realm-export.json
      - ./configs/keycloak/themes/ho-theme:/opt/jboss/keycloak/themes/ho-theme
  
  ho-vault:
    container_name: ho-vault
    image: vault:1.12.0
    ports:
      - "8200:8200"
    restart: always
    environment: 
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
    restart: always
    volumes:
      - ./configs/vault/volumes/logs:/vault/logs
      - ./configs/vault/volumes/file:/vault/file
      - ./configs/vault/volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

  ho-config-server:
    container_name: ho-config-server
    image: ghcr.io/tegridy/config-server:0.1
    ports:
      - 8888:8888
    environment:
      - VAULT_URL=ho-vault
      - VAULT_PORT=8200
    restart: always 

  ho-api-gateway:
    container_name: ho-api-gateway
    image: api-gateway:1.0  
    ports:
      - '9090:9090'
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server

  ho-discovery-service:
    container_name: ho-discovery-service
    image: discovery-service:1.0
    ports:
      - 8761:8761
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always

  ho-postgresql-hackathon-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5434:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=qwerty
      - POSTGRESQL_DATABASE=hackathon_db
    restart: always

  ho-postgresql-user-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=qwerty
      - POSTGRESQL_DATABASE=user_db
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  ho-postgresql-user-slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5433:5432'
    depends_on:
      - ho-postgresql-user-master
    environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_REPLICATION_USER=repl_user
        - POSTGRESQL_REPLICATION_PASSWORD=repl_password
        - POSTGRESQL_MASTER_HOST=ho-postgresql-user-master
        - POSTGRESQL_PASSWORD=qwerty
        - POSTGRESQL_MASTER_PORT_NUMBER=5432
        - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  ho-postgresql-messaging-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5435:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=qwerty
      - POSTGRESQL_DATABASE=messaging_db
    restart: always

  ho-media-server:
    image: openvidu/openvidu-dev:2.24.0
    ports:
      - '4443:4443'
    environment:
      - OPENVIDU_SECRET=secret
    restart: always

  ho-hackathon-write-service:
    image: hackathon-write-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always  
    depends_on:
      - ho-discovery-service
      - ho-config-server
    volumes:
      - ./var/files:/var/files

  ho-hackathon-read-service:
    image: hackathon-read-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888  
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server  
    volumes:
      - ./var/files:/var/files

  ho-user-write-service:
    image: user-write-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888 
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server

  ho-user-read-service:
    image: user-read-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always 
    depends_on:
      - ho-discovery-service
      - ho-config-server

volumes:
  postgresql_master_data:
    driver: local

