version: '3.1'

services:
  ho-rabbitmq3:
      container_name: "ho-rabbitmq"
      image: rabbitmq:3.11.9-management-alpine
      environment:
          - RABBITMQ_DEFAULT_USER=${RABBIT_LOGIN}
          - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      restart: always
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
        - ./prod/configs/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./prod/configs/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro

  ho-keycloak:
    container_name: ho-keycloak
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_LOGIN}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KK_TO_RMQ_URL=ho-rabbitmq
      - KK_TO_RMQ_PORT=5672
      - KK_TO_RMQ_USERNAME=${RABBIT_LOGIN}
      - KK_TO_RMQ_PASSWORD=${RABBIT_PASSWORD}
      - KK_TO_RMQ_VHOST=/
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    restart: always
    volumes:
      - ./prod/resources/keycloak-to-rabbit-3.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-3.0.jar
      - ./prod/configs/keycloak/realm-export.json:/tmp/realm-export.json
      - ./prod/configs/keycloak/themes/ho-theme:/opt/jboss/keycloak/themes/ho-theme
  
  ho-vault:
    container_name: ho-vault
    image: vault:1.12.0
    ports:
      - 8200:8200
    restart: always
    volumes:
      - ./prod/configs/vault/volumes/logs:/vault/logs
      - ./prod/configs/vault/volumes/file:/vault/file
      - ./prod/configs/vault/volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

  ho-config-server:
    container_name: ho-config-server
    image: ghcr.io/tegridy/config-server:1.0
    ports:
      - 8888:8888
    environment:
      - VAULT_HOST=ho-vault
      - VAULT_PORT=8200
      - VAULT_TOKEN=${VAULT_TOKEN}
    restart: always 

  ho-api-gateway:
    container_name: ho-api-gateway
    image: api-gateway:1.0  
    ports:
      - 9090:9090
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server

  ho-discovery-service:
    container_name: ho-discovery-service
    image: ghcr.io/tegridy/discovery-service:1.0
    ports:
      - 8761:8761
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always

  ho-postgresql-hackathon-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_LOGIN}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=hackathon_db
    restart: always

  ho-postgresql-user-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5432:5432
    volumes:
      - postgresql_master_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${DB_LOGIN}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=user_db
    restart: always

  ho-postgresql-messaging-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - 5435:5432
    environment:
      - POSTGRESQL_USERNAME=${DB_LOGIN}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=messaging_db
    restart: always

  ho-messaging-service:
    image: ghcr.io/tegridy/messaging-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    depends_on:
      - ho-discovery-service
      - ho-config-server

  ho-media-server:
    image: openvidu/openvidu-dev:2.24.0
    ports:
      - 4443:4443
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
    restart: always

  ho-hackathon-write-service:
    image: ghcr.io/tegridy/hackathon-write-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always  
    depends_on:
      - ho-discovery-service
      - ho-config-server
    volumes:
      - ./prod/var/files:/var/files

  ho-hackathon-read-service:
    image: ghcr.io/tegridy/hackathon-read-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888  
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server  
    volumes:
      - ./prod/var/files:/var/files

  ho-user-write-service:
    image: ghcr.io/tegridy/user-write-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888 
    restart: always
    depends_on:
      - ho-discovery-service
      - ho-config-server

  ho-user-read-service:
    image: ghcr.io/tegridy/user-read-service:1.0
    environment:
      - CONFIG_SERVER_HOST=ho-config-server
      - CONFIG_SERVER_PORT=8888
    restart: always 
    depends_on:
      - ho-discovery-service
      - ho-config-server

volumes:
  postgresql_master_data:
    driver: local

